
/*

>>Relacion (1:1)
Los motores se identifican por un ID 
Un auto solo puede tener un motor y un motor identificado solo puede pertenecer a un auto


*/

CREATE DATABASE RELACION_1A1
GO
USE RELACION_1A1
GO

CREATE TABLE MOTORES(
    IDMOTOR INT NOT NULL, --PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    COMBUSTIBLE CHAR(1) NOT NULL, --CHECK (COMBUSTIBLE = 'G' OR COMBUSTIBLE = 'N'), --G = Gas y N = Nafta
    CILINDROS SMALLINT NOT NULL 
)
GO
CREATE TABLE AUTOS(
    ID_MOTOR INT NOT NULL, --PRIMARY KEY,
    --FOREIGN KEY (ID_MOTOR) REFERENCES MOTORES(IDMOTOR),
    PUERTAS SMALLINT NULL,
    ANIO INT NULL --CHECK (ANIO>=1886 AND ANIO<= YEAR(GETDATE())) --1886 -> Se invento el primer auto ;)
)
GO

ALTER TABLE MOTORES
ADD CONSTRAINT PK_IDMOTOR PRIMARY KEY (IDMOTOR)
ALTER TABLE MOTORES
ADD CONSTRAINT CHK_COMBUSTIBLE CHECK (COMBUSTIBLE = 'G' OR COMBUSTIBLE = 'N') --G = Gas y N = Nafta)

GO

ALTER TABLE AUTOS
ADD CONSTRAINT PK_ID_MOTOR PRIMARY KEY (ID_MOTOR)
ALTER TABLE AUTOS
ADD CONSTRAINT FK_MOTORID FOREIGN KEY (ID_MOTOR) REFERENCES MOTORES(IDMOTOR)
ALTER TABLE AUTOS
ADD CONSTRAINT CHK_ANIO CHECK (ANIO>=1886 AND ANIO<= YEAR(GETDATE()))