/*
>>Relacion (1:N)

Una prende puede tener una sola linea y temporada, y varias prendas pueden pertenecer a las mismas lineas y/o temporadas

*/

CREATE DATABASE RELACION_1AN
GO
USE RELACION_1AN
GO
CREATE TABLE TEMPORADAS (
    ID_TEMPORADA INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR (50),
)
GO

CREATE TABLE LINEA (
    ID_LINEA INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR (50),
)

GO

CREATE TABLE PRENDAS (
    ID_PRENDA INT NOT NULL PRIMARY KEY,
    TEMPORADA INT NOT NULL FOREIGN KEY REFERENCES TEMPORADAS(ID_TEMPORADA),
    LINEA INT NOT NULL FOREIGN KEY REFERENCES LINEA(ID_LINEA),
    FECHA_INGRESO DATE NOT NULL CHECK (FECHA_INGRESO <= GETDATE())

)